global:
  scrape_interval:     5s
  evaluation_interval: 10s
  external_labels:
    monitor: node
scrape_configs:
  - job_name: api-products
    honor_labels: true
    static_configs:
    - targets: ['api-products:5000']