version: "3"
services:
  xald-app:
    build:
      context: ./xald-app
    container_name: c-xald-app
    image: xald-app
    stdin_open: true
    ports: 
      - 82:3000
    networks:
      - xal-digital
    volumes:
      - ".:/usr/src/app"
    environment:
      - REACT_APP_ENV=production
      - REACT_APP_VERSION=2.0.0-compose
      - REACT_APP_API_ANSWERS=http://localhost:84/api/answers
      - REACT_APP_API_AIRPORTS=http://localhost:84/api/airports
  api-answers:
    build:
      context: ./api-answers
    container_name: c-api-answers
    image: api-answers
    env_file:
      - ./api-answers/.env
    ports:
      - "83:5000"
    networks:
      - xal-digital
    environment:
      FLASK_ENV: development
      DB_CONN_STRING: mongodb+srv://user_dev:s4YDLwExGsQmibMK@freecluster.9td3h.mongodb.net/xaldigital?retryWrites=true&w=majority
    depends_on:
      - mongo
  prometheus:
    build:
      context: ./my-prometheus
    container_name: c-prometheus
    image: my-prometheus
    ports: 
      - "9091:9090"
    networks:
      - xal-digital
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - xal-digital
networks:
  xal-digital:
    driver: bridge